- examples/receiver.rs
- examples/sender.rs
- src/cli.rs
- src/ildcp.rs
- src/plugin/btp/client.rs
- src/plugin/btp/ilp_packet_stream.rs
- src/plugin/btp/packet_stream.rs
- src/spsp.rs
- src/stream/congestion.rs
- src/stream/connection.rs
- src/stream/crypto.rs
- src/stream/data_money_stream.rs
- src/stream/listener.rs
- src/stream/mod.rs
- src/stream/packet.rs
Unfortunately, `rustfmt` included some changes.
Notable changes include:
- using `MutBufOerExt` to remove unnecessary Results in `src/stream/packet.rs`
- removal of `unwrap()` functions in `src/stream/connection.rs`
- using `expect()` instead of `unwrap()` in `crypto.rs`
- use `?` operator on `std::collections::Hashmap` instead of `unwrap()` in `src/stream/data_money_stream.rs
`
Sorry for the `rustfmt` inconvenience. Thank you for any additional feedback!
> refactor(stream): make serialization not return a Result

- crates/interledger-service-util/Cargo.toml
- crates/interledger-service-util/src/balance_service.rs
Fixes #92. The log in case the store operation failed should be moved in the respective implementation of each store.
> Propagate packet to next peer instead of waiting for store operation to finish

- crates/interledger/tests/redis_helpers.rs
Fixes #143.
Secretly this PR is also intended to test whether or not CI is set up to look for new dependencies automatically, since a new patch version of crossbeam (which we transitively depend on) has been released to address an objection by cargo-audit, which we gate our CI on and which would previously cause PRs to be rejected spuriously. I assume this is the case, unless CI is trying to do some sneaky caching or something.
> Better error message when running tests without redis

- crates/interledger-api/src/routes/accounts.rs
- crates/interledger-settlement-engines/src/engines/ethereum_ledger/eth_engine.rs
- crates/interledger-settlement-engines/src/engines/ethereum_ledger/test_helpers.rs
- crates/interledger-settlement-engines/src/engines/ethereum_ledger/types.rs
- crates/interledger-settlement-engines/src/engines/ethereum_ledger/utils.rs
- crates/interledger-settlement-engines/src/stores/redis_ethereum_ledger/store.rs
- crates/interledger-store-redis/src/store.rs
- examples/pay_dump.sh
- examples/settlements_test.sh
Fixes most of https://github.com/emschwartz/interledger-rs/issues/149
TODO: Add more tests for SPSP payments in `interledger` similar to `three_nodes.rs`
> Ethereum Settlement Engine improvements

- crates/interledger-btp/Cargo.toml
- crates/interledger-btp/src/service.rs
- crates/interledger-ccp/Cargo.toml
- crates/interledger-ccp/src/lib.rs
- crates/interledger-ccp/src/routing_table.rs
- crates/interledger-ccp/src/server.rs
- crates/interledger-ccp/src/test_helpers.rs
- crates/interledger-router/Cargo.toml
- crates/interledger-router/src/lib.rs
- crates/interledger-router/src/router.rs
- crates/interledger-store-memory/Cargo.toml
- crates/interledger-store-memory/src/store.rs
- crates/interledger-store-redis/Cargo.toml
- crates/interledger-store-redis/src/store.rs
- crates/interledger-stream/Cargo.toml
- crates/interledger-stream/src/lib.rs
Note that this involves changing a HashMap to a Vec in interledger-ccp, because we were implicitly relying on things being iterated upon in insertion order which is not something that HashMaps usually guarantee, leading to flaky tests upon switching implementations.
I would like someone who is more well-versed in the interledger-ccp logic to take a look at the changes there, since the switch from HashMap to Vec seemed a bit *too* easy. My worry is that there might be some implicit invariants that I'm not entirely sure are still upheld (though if not then I do at least think that the prior implementation may not have been intentionally upholding them either, so it's probably no *more* incorrect than it used to be). See my PR-level comments below for particular cases.
Fixes #130
> Remove dependence on hashbrown

- crates/interledger-api/src/lib.rs
- crates/interledger-api/src/routes/accounts.rs
- crates/interledger-store-redis/src/store.rs
- crates/interledger-store-redis/tests/accounts_test.rs
Adds a new HTTP endpoint that allows the admin of a node to delete accounts on that node.
Part of https://github.com/emschwartz/interledger-rs/issues/196
> feat: deletion of accounts from nodes

- crates/interledger-settlement-engines/Cargo.toml
- crates/interledger-settlement-engines/src/engines/ethereum_ledger/eth_engine.rs
- crates/interledger-settlement-engines/src/engines/ethereum_ledger/mod.rs
- crates/interledger-settlement-engines/src/engines/ethereum_ledger/test_helpers.rs
- crates/interledger-settlement-engines/src/engines/ethereum_ledger/types.rs
- crates/interledger-settlement-engines/src/engines/ethereum_ledger/utils.rs
- crates/interledger-settlement-engines/src/stores/redis_ethereum_ledger/store.rs
https://github.com/gakonst/ethereum-tx-sign is still being used until the maintainer merges https://github.com/synlestidae/ethereum-tx-sign/pull/10
> update dependencies to use upstream crates

- crates/interledger-service-util/Cargo.toml
- crates/interledger-service-util/src/validator_service.rs
Related to https://github.com/emschwartz/interledger-rs/issues/109
I'm not sure whether switching to `chrono` will solve the problem, but a) it might and b) the logs will be a bit more readable if it does.
Unfortunately the issue identified in #109 is hard to reproduce and it's unclear why it happens so I can't think of a better fix for it now. Anyone else have other ideas? If not, we could merge this and wait to see if the problem still arises in future builds.
> Use chrono for date parsing and comparisons in the validator

- examples/eth-settlement/README.md
- examples/eth_xrp_three_nodes/README.md
- Examples got broken because account specs have been changed.
- Settlement examples output adding account logs into files so that account id could be obtained later.
- This kind of problem could be avoided if once we add example tests.
> Fix example bug

- crates/interledger-packet/src/oer.rs
- crates/interledger-stream/src/packet.rs
* `read_var_octet_string_length`: Don't panic when the length prefix length is more than 8 bytes; return an error instead.
* `read_var_uint`: Don't panic when the value's length is more than 8 bytes; return an error instead.
Comply with [ILP-RFC-29 §5.1.4](https://github.com/interledger/rfcs/blob/master/0029-stream/0029-stream.md#514-maximum-varuint-size) to properly handle values larger than `u64`:
> If an implementation does not support larger `VarUInt`s, it MUST:
> * When decoding a `StreamMaxMoney` frame, if the `receiveMax` is too large to fit in a `UInt64`, decode `receiveMax` as `MaxUInt64`.
> * When decoding a `StreamMoneyBlockedFrame` frame, if the `sendMax` is too large to fit in a `UInt64`, decode `sendMax` as `MaxUInt64`.
> fix(stream,packet): var_octet_string_length: dont panic

- crates/interledger-store-redis/Cargo.toml
- crates/interledger-store-redis/src/account.rs
Turns out URLv2 with serde feature flag on is sufficient for any serialization, https://github.com/servo/rust-url/issues/545
> Remove url serde

- crates/interledger-api/Cargo.toml
- crates/interledger-api/README.md
- crates/interledger-btp/Cargo.toml
- crates/interledger-btp/README.md
- crates/interledger-ccp/Cargo.toml
- crates/interledger-ccp/README.md
- crates/interledger-http/Cargo.toml
- crates/interledger-ildcp/Cargo.toml
- crates/interledger-packet/Cargo.toml
- crates/interledger-router/Cargo.toml
- crates/interledger-service-util/Cargo.toml
- crates/interledger-service/Cargo.toml
- crates/interledger-settlement-engines/Cargo.toml
- crates/interledger-settlement-engines/tests/eth_xrp_interoperable.rs
- crates/interledger-settlement-engines/tests/test_helpers.rs
- crates/interledger-settlement-engines/tests/xrp_ledger_settlement.rs
- crates/interledger-settlement/Cargo.toml
- crates/interledger-spsp/Cargo.toml
- crates/interledger-store-memory/Cargo.toml
- crates/interledger-store-redis/Cargo.toml
- crates/interledger-stream/Cargo.toml
- crates/interledger/Cargo.toml
- scripts/run-md.sh
I needed to update serde to get https://github.com/interledger-rs/interledger-rs/pull/247 working locally.
> Update serde + dynamically fetch XRP credentials

- crates/interledger-service/Cargo.toml
- crates/interledger-service/src/auth/username.rs
- examples/simple/README.md
The new username feature doesn't allow names to contain special
characters other than underscore, but the simple example had usernames
of the form "node-a". However, this was only being detected during
account lookup, whereas account creation was bypassing the validation
check. This occurred because the intended function by which to construct
a valid instance of Username, `Username::from_str`, was being explicitly
invoked during account lookup; for account creation, the instance of
Username was constructed directly via the Deserialize implementation
generated by Serde. Serde has an attribute hook that allows types to run
custom validation logic via the TryFrom trait; we implement TryFrom for
Username here in terms of the existing FromStr impl (in some future
version of Rust this may be …
> fix(service, examples): reject invalid usernames during account creation

- crates/interledger-settlement-engines/src/engines/ethereum_ledger/eth_engine.rs
- crates/interledger-settlement-engines/src/main.rs
- crates/interledger-settlement-engines/tests/eth_ledger_settlement.rs
- crates/interledger-settlement-engines/tests/eth_xrp_interoperable.rs
- crates/interledger-settlement-engines/tests/test_helpers.rs
**This PR should be merged after #236 is merged**
Specifying a port for the settlement engine is not sufficient because sometimes we need to
specify the address, for example, running on Docker.
BREAKING CHANGE: Now --port option is obsolete, use http_address instead.
> feat(eth se): port is deprecated, use http_address instead

- crates/interledger-api/Cargo.toml
- crates/interledger-api/src/client.rs
- crates/interledger-api/src/lib.rs
- crates/interledger-api/src/routes/accounts.rs
- crates/interledger-settlement-engines/Cargo.toml
- crates/interledger-settlement-engines/src/engines/ethereum_ledger/eth_engine.rs
- crates/interledger-settlement-engines/tests/eth_ledger_settlement.rs
- crates/interledger-settlement-engines/tests/eth_xrp_interoperable.rs
- examples/eth-settlement/README.md
- examples/eth_xrp_three_nodes/README.md
- examples/xrp_ledger/README.md
- examples/xrp_ledger/xrp_settlements_test.sh
Closes https://github.com/interledger-rs/interledger-rs/issues/212
It always does exponential backoff now. 
@emschwartz described the following behavior:
> exp backoff, 10 retries ONLY on temporary errors, stops on final errors but returns 202 Accepted if the error was the equivalent of a 404 Not Found)
[RetryIf](https://docs.rs/tokio-retry/0.2.0/tokio_retry/struct.RetryIf.html) might be usable for the above, or although futures-retry probably has a better API: https://gitlab.com/mexus/futures-retry/blob/master/examples/tcp-client.rs. Which status codes do we want to retry and which not?
> Allow accounts to be created at different times

- crates/interledger-settlement-engines/src/main.rs
- crates/interledger/src/cli.rs
- crates/interledger/src/main.rs
- crates/interledger/src/node.rs
Resolves https://github.com/interledger-rs/interledger-rs/issues/300
> Propagate panics from tokio

- crates/interledger-api/src/lib.rs
- crates/interledger-store-redis/src/account.rs
- crates/interledger-store-redis/src/store.rs
Removes any cryptography related operations from the underlying redis store implementation. The NodeStore implementer must perform any encryption related operations. The underlying store must operate only on encrypted data.
Part of https://github.com/interledger-rs/interledger-rs/issues/195 & https://github.com/interledger-rs/interledger-rs/issues/108
> Separate crypto operations from redis

- crates/interledger-api/src/lib.rs
- crates/interledger-api/src/routes/accounts.rs
This PR extracts the node-side pieces of #334 that allow clients of the HTTP API to choose to pass strings where numbers are expected. Has already incorporated feedback from #334 so should not be difficult to review.
> feat: allow endpoints to accept strings or numbers in JSON

- crates/ilp-node/src/node.rs
- crates/interledger-http/src/client.rs
- crates/interledger-router/src/router.rs
- crates/interledger-service-util/src/balance_service.rs
- crates/interledger-service-util/src/echo_service.rs
- crates/interledger-service-util/src/exchange_rates_service.rs
- crates/interledger-service-util/src/max_packet_amount_service.rs
- crates/interledger-service-util/src/rate_limit_service.rs
- crates/interledger-service-util/src/validator_service.rs
- crates/interledger-settlement/src/message_service.rs
- crates/interledger-settlement/src/test_helpers.rs
- crates/interledger-stream/src/lib.rs
Previously we were constructing the value once, and did not account for any changes to the node's ilp address due to adding a parent.
> Fetch ILP Address from the store

- crates/interledger-ccp/src/server.rs
- crates/interledger-service-util/src/expiry_shortener_service.rs
- crates/interledger-store-redis/src/store.rs
Minor PR but looking through the testnet node logs, they are currently filled with output from a couple of these log lines
> Reduce CCP log chattiness

- .circleci/config.yml
- crates/interledger-settlement-engines/tests/eth_xrp_interoperable.rs
- crates/interledger-settlement-engines/tests/test_helpers/mod.rs
- crates/interledger-settlement-engines/tests/xrp_ledger_settlement.rs
- examples/eth-xrp-three-nodes/README.md
- examples/xrp-settlement/README.md
Blocked until `ilp-settlement-core` and `ilp-settlement-xrp` are published to NPM.
The new version simplifies some of the configuration, since testnet XRP accounts are automatically generated if no credentials are supplied.
> Update XRP examples and tests to new SE version

- crates/interledger-ccp/src/lib.rs
- crates/interledger-ccp/src/server.rs
- crates/interledger-ccp/src/test_helpers.rs
- crates/interledger-store-redis/src/reconnect.rs
- crates/interledger-store-redis/src/store.rs
- crates/interledger-store-redis/tests/routing_test.rs
Right now the testnet node wastes a lot of resources trying to broadcast routes to all of the child accounts, many of whom are offline (because they use localtunnel to connect). This changes the behavior such that it will back off from sending route updates to child accounts when the requests fail. This does not affect the behavior for Peer accounts.
> Don't broadcast routes to unavailable accounts

- crates/ilp-cli/src/interpreter.rs
- docs/testnet.md
As title. Rewords the doc from #314 and uses the `ilp-cli` instead of manual curl requests.
> Add testnet docs

- README.md
Signed-off-by: Kevin W Matthews <kevinwmatthews@gmail.com>
> docs(readme): fix typo - run container instead of pulling

- docker/node.dockerfile
- examples/simple/README.md
Docker mode of simple example is not working because of multiple problems.
1. `node.dockerfile` is wrong, it should not specify `node` for arguments.
1. Checking balance commands are not working, `ilp-cli` command is not found on Docker mode.
- Specifying `ilp-cli` in Docker mode looked inefficient because we have to compile.
- Using `curl` might be another option but using Docker image of `ilp-cli` looked suitable also.
Because `ilp-cli` needs `--rm` option, this might be not so efficient. Needs to be fixed in the future.
> fix(example): fix docker mode of simple example

- docker/Dockerfile
- docker/run-testnet-bundle.js
Now that the node is bound to `0.0.0.0`, we can bind localhost's 7770 to the container's 7770.
Also includes changes for the settlement engine repo change.
> feat(testnet docker bundle): accepts http_bind_address from env and defaults to `0.0.0.0:7770`

- Cargo.lock
- crates/interledger-btp/Cargo.toml
TLS is not enabled for BTP as reported [here](https://interledger.slack.com/archives/CHC51E54J/p1570774735020000?thread_ts=1570729525.012400&cid=CHC51E54J), this PR fixes it.
> fix(btp, cargo.toml): enable TLS

- examples/eth-xrp-three-nodes/README.md
- scripts/run-md-lib.sh
This is originally a part of #305 but I feel like we should not leave this, people are struggling to try out `interledger-rs`.
Cloning settlement-engines inside interledger-rs is not good because it causes an error. In
addition, node setting of Charlie is wrong.
> fix(three node example): fixes three node example

- Cargo.lock
- crates/ilp-node/Cargo.toml
- crates/ilp-node/src/node.rs
- crates/ilp-node/tests/btp.rs
- crates/ilp-node/tests/exchange_rates.rs
- crates/ilp-node/tests/prometheus.rs
- crates/ilp-node/tests/redis_helpers.rs
- crates/ilp-node/tests/test_helpers.rs
- crates/ilp-node/tests/three_nodes.rs
- crates/interledger-http/src/client.rs
- crates/interledger-service-util/src/exchange_rates_service.rs
- crates/interledger-service/src/lib.rs
Resolves https://github.com/interledger-rs/interledger-rs/issues/139
**Updated:**
This exposes metrics in the Prometheus format when the `prometheus` details are configured on the node.
Currently, it collects the following statistics:
- the number of incoming/outgoing Prepares, Fulfills, and Rejects
- the amount of time it took to service incoming requests
- the amount of time it took other nodes to respond to outgoing requests
- all of the above statistics are broken out by asset code and routing relation (parent, peer, child)
Note that if the `prometheus` configuration is not provided to the node, no metrics will be collected. This means that running the node with metrics turned off should have near zero performance overhead.
> Add Prometheus metrics

- Cargo.lock
- crates/ilp-node/Cargo.toml
- crates/ilp-node/src/node.rs
Most pertinently this removes some obsolete transitive dependencies on hashbrown and parking_lot.
> chore: update metrics-rs to new version

- Cargo.lock
- crates/ilp-node/Cargo.toml
- crates/interledger-api/Cargo.toml
- crates/interledger-service-util/Cargo.toml
- crates/interledger-store-redis/Cargo.toml
The secrecy crate recently released both 0.4.1 and 0.5.0. We're on 0.4.0, but it turns out that 0.4.1 is accidentally a semver-incompatible release, which means that any `cargo update` right now is going to fail. I figure now's as good a time as any to update the dependency.
> chore: update secrecy to v0.5.0

- crates/interledger-api/src/routes/node_settings.rs
- docs/api.md
Resolves: #452
Can't we just use `CARGO_PKG_VERSION`?
> fix(health-check api): fix to return a correct semantic version

- Cargo.lock
- crates/ilp-node/Cargo.toml
- crates/ilp-node/src/node.rs
- crates/interledger-ccp/Cargo.toml
- crates/interledger-service-util/Cargo.toml
- crates/interledger-settlement/Cargo.toml
- crates/interledger-store-redis/Cargo.toml
- crates/interledger-store-redis/src/account.rs
- crates/interledger-store-redis/src/crypto.rs
- crates/interledger-stream/Cargo.toml
- crates/interledger-stream/src/crypto.rs
As explained in https://github.com/interledger-rs/interledger-rs/issues/407, the `ring` dependency latest version is `0.16.9`, which involves breaking changes in method signatures with the `0.14.6` version `interledger-rs` is using.
This PR
- upgrades the `ring` dependency to `0.16.9` and
- migrates existing code to adopt the new method signature.
I am quite new to Rust so please let me know if anything can be improved. I am more than happy to try to change it to keep up with the standard here.
> Upgrade ring to 0.16.9

- docs/CONTRIBUTING.md
`CONTRIBUTING.md` contains a link to the Interledger Rust Slack channel but new users don't have access without an account. Add a link to make it easy to join the Interledger Slack workspace.
> Add link to join Interledger Slack workspace

- crates/ilp-node/tests/test_helpers.rs
- crates/ilp-node/tests/three_nodes.rs
- crates/interledger-api/src/routes/accounts.rs
- crates/interledger-api/tests/accounts.rs
- crates/interledger-spsp/src/client.rs
- crates/interledger-stream/Cargo.toml
- crates/interledger-stream/src/client.rs
- crates/interledger-stream/src/crypto.rs
- crates/interledger-stream/src/lib.rs
- crates/interledger-stream/src/server.rs
- docs/api.md
Closes https://github.com/interledger-rs/interledger-rs/issues/419. 
Uses the `ConnectionAssetDetails` frame to return additional useful information to the sender.
Running the simple example:
```
Sending payment of 500 from Alice (on Node A) to Bob (on Node B)...
{
"delivered_asset_scale" : 9,
"delivered_asset_code" : "ABC",
"sent_amount" : 500,
"sent_asset_code" : "ABC",
"from" : "example.node_a.alice",
"to" : "example.node_b.bob.-p3zU4tXsDRCBLg8vt_U6iiyQ5pgZk4MfoCaG1wZDW8",
"delivered_amount" : 500,
"sent_asset_scale" : 9
}
```
> Enhance details when sending an SPSP payment

- Cargo.lock
- crates/ilp-node/src/main.rs
- crates/ilp-node/tests/btp.rs
- crates/ilp-node/tests/exchange_rates.rs
- crates/ilp-node/tests/prometheus.rs
- crates/ilp-node/tests/three_nodes.rs
- crates/interledger-api/src/routes/node_settings.rs
- crates/interledger-ccp/src/fixtures.rs
- crates/interledger-ccp/src/lib.rs
- crates/interledger-ccp/src/packet.rs
- crates/interledger-ccp/src/routing_table.rs
- crates/interledger-ccp/src/server.rs
- crates/interledger-ccp/src/test_helpers.rs
- crates/interledger-router/Cargo.toml
- crates/interledger-router/src/lib.rs
- crates/interledger-router/src/router.rs
- crates/interledger-store-redis/src/store.rs
- crates/interledger-store-redis/tests/routing_test.rs
- crates/interledger-stream/src/lib.rs
While reviewing the routing table logic with @bstrie, we realized that it was cloning the whole routing table, including account IDs for every account, while processing each packet. This changes the `RouterStore#routing_table()` method to return an `Arc<HashMap>` to avoid copying the underlying data.
This also changes the prefix type to be `String`s instead of `Bytes`, because ILP address prefixes must be UTF8 and we had a lot of unnecessary parsing logic scattered throughout the code to display the prefix.
The first two commits are unrelated but they're small changes I think we should make.
Open questions:
- Should we use the [String crate](https://crates.io/crates/string) instead of `std::string::String` to avoid copying those values around (for example, when creating route broadcasts)?
> Don't clone routing table for every packet

- Cargo.lock
- Cargo.toml
- crates/ilp-node/Cargo.toml
- crates/interledger-service/Cargo.toml
we no longer need the patch because the features we depended on were included in the latest releases of those crates
> Use tracing-subscriber v0.1.6, tracing-futures v0.1.1

- crates/interledger-ccp/src/server.rs
Fix: `two_nodes_btp` is unstable #464
Currently `better_routes` is set with the old account information. It should be replaced with the latest best route. This bug makes the `two_nodes_btp` test unstable. The reason is a bit complex, there are 2 types of behavior.
1. Success pattern
- Node A sends an ILDCP request to Node B
- **Node A has not received Route Update Request at this point**
- Node A receives ILDCP response
- The local table finally becomes like:
- `example.parent.a_on_b.alice_on_a`: `alice_on_a`
1. Failure pattern
- Node A sends an ILDCP request to Node B
- **Node A receives a Route Update Request** and the local table becomes like:
- `example.parent`: `b_on_a`
- This is correct at this point though I'm not sure this is the desired behavior or not
- Node A receives ILDCP …
> fix(ccp): fix to update the local table correctly, respecting the best route

- crates/ilp-node/tests/three_nodes.rs
- crates/interledger-service-util/src/exchange_rates_service.rs
We were upscaling instead of downscaling when converting between assets.
example:
ABC is worth $1 USD
XYZ is worth $10 USD
from = ABC
to = XYZ
previously:
rates[0] = 1
rates[1] = 10
rates[1]/rates[0] = 10
For each unit of ABC we would send out 10 units of XYZ, while instead we should be sending 0.1 unit. This is wrong.
We fix that by reverting the numerator with the denominator. Now, rates[0]/rates[1] = 0.1, which represents the correct amount whcih we should be sending.
--
In the opposite case:
from = XYZ
to = ABC
rates[0] = 10
rates [1] = 1
rates[0]/rates[1] = 10, which means that for each unit of XYZ we should send 10 units of ABC, which now makes perfect sense
> Fix exchange rate bug

- Cargo.lock
- crates/ilp-cli/Cargo.toml
- crates/ilp-cli/src/interpreter.rs
- crates/ilp-cli/src/main.rs
The cli app will panic in `ws_account_payments_incoming` for several legitimate use cases:
* invalid URL
* invalid URL protocol/scheme
* ilp node not running
This extends the `interpreter.rs` module's `Error` enum, allowing the `?` to gracefully report failures to the end user. Is this the style you prefer for error handling?
A few other notes:
* Refactored a nested match statement for readability, drawn from this [clap example](https://docs.rs/clap/2.33.0/clap/struct.ArgMatches.html#examples-13). The behavior should be the same.
* Is there a more descriptive name for `ClientErr`, say, `RequestErr`?
* Can `socket.read_message().expect("Could not receive WebSocket message")` occur in normal use?
* Is there is a reasonable way to spin up an ilp node for testing runtime failures? There …
> Update error handling in cli-app

- crates/interledger-service-util/src/exchange_rate_providers/cryptocompare.rs
Currently the `exchange_rates` test fails because `MEXC` doesn't have the `RAW` field.
```
2019-11-06T02:31:55.616780071+00:00 ERROR interledger_service_util::exchange_rate_providers::cryptocompare: Error getting exchange rate response body from CryptoCompare, incorrect type: Error(Json(Error("missing field `RAW`", line: 1, column: 104464)))    
```
https://circleci.com/gh/interledger-rs/interledger-rs/3188
> fix(cryptocompare): ignore currencies that don't have the RAW field

- crates/ilp-node/src/node.rs
- crates/interledger-api/src/lib.rs
- crates/interledger-api/src/routes/node_settings.rs
We could do some hack when compiling using `build.rs` etc. but it seemed more straightforward to pass the version to API. I'm not so sure there is the case of using `interledger-api` crate for another use but I used `Option` for `node_version`. If that looks too much or unnecessary, I'd be happy to change.
The output looks like:
```
{"ilp_address":"local.host","status":"Ready","version":"0.5.1"}
```
which shows `ilp-node`'s version.
> feat(http api): return the node version instead of the interledger-api crate version

- crates/interledger-settlement/src/api/node_api.rs
- crates/interledger-settlement/src/api/test_helpers.rs
- crates/interledger-settlement/src/core/backends_common/redis/mod.rs
- crates/interledger-settlement/src/core/engines_api.rs
- crates/interledger-settlement/src/core/idempotency.rs
- crates/interledger-settlement/src/core/types.rs
- crates/interledger-store-redis/src/store.rs
- crates/interledger-store-redis/tests/settlement_test.rs
- The StatusCode does not depend on the engine implementation. As a result we remove it from the engines trait
- The only settlement functions which return data is the message-related ones. We abstract over the return type with an enum, and make the idempotent.
- Taking the above into account, we add a status code & default return data to the idempotent call
- All tests are adjusted to take that into account
Depends on #497.
> Update Settlement API to master RFC

- .circleci/config.yml
- Cargo.lock
- crates/ilp-cli/Cargo.toml
- crates/ilp-node/Cargo.toml
- crates/ilp-node/src/google_pubsub.rs
- crates/ilp-node/src/lib.rs
- crates/ilp-node/src/main.rs
- crates/ilp-node/src/node.rs
- crates/interledger-service-util/Cargo.toml
This is an experimental feature for publishing fulfilled packets to a message queue (in this case, Google's hosted PubSub service). This can be used as an alternative to real-time balance tracking because the amounts of the fulfilled packets can be summed up later to determine the balances with specific peers.
It's possible this will be removed later or we may abstract the behavior more so it's not so tied to Google Cloud.
> Optional feature to publish packets to Google PubSub

- Cargo.lock
- crates/interledger-http/Cargo.toml
- crates/interledger-http/src/lib.rs
Fix: #498 
Now the `deserialize_json` filter accepts `content-type` header with `charset` arguments.
> feat(http api): accepts content-type with arguments

- examples/eth-settlement/README.md
- examples/eth-xrp-three-nodes/README.md
Fix: #523
Now the `test-md` test is failing because we use `ilp-settlement-ethereum` now.
This PR fixes it.
> docs(eth examples): fix to use the "ilp-settlement-ethereum" bin

- .circleci/config.yml
I'm sorry but there was a bug in CI.
Currently the variable is referring to `CIRCLE_TAG`, which is not correct. It should be
`CIRCLE_BRANCH` if we want to make a release on the `master` branch.
> ci(circleci): fix to make a release when the branch is `master`

- docker/Dockerfile
- docker/run-testnet-bundle.js
Fix to use `ilp-settlement-ethereum` binary for the testnet-bundle docker image.
Also add settings to output logs of settlement-engines because it currently does not.
We should consider https://github.com/interledger-rs/settlement-engines/issues/23 later.
> fix(testnet-bundle): fixed to use the ilp-settlement-ethereum binary

- crates/ilp-node/src/main.rs
- docs/api.md
- docs/configuration.md
Fix: #472
Add node config explanation, and also fix the wrong explanation of CLI.
Maybe I should add the same thing for `interledger-settlement-engines`.
(I didn't add the pubsub config because it seemed an experimental feature)
> feat(node cli explanation, docs): add node config explanation, fix node cli explanation

- crates/ilp-node/tests/btp.rs
The problem detail is here #464
The problemn is that `ilp_address` and the ILP address of an account that is being inserted are not
treated as fully atomic. It should be fixed later after SQL store is integrated. This fix is not an
essential solution and just a temporary work-around, not to let the test fail.
> test(two_nodes_btp): work-around for inserting account atomicity problem #464

- .github/CODEOWNERS
- README.md
- docs/configuration.md
- docs/manual-config.md
- Remove `interledger-settlement-engines` from CODEOWNERS
- Fix README to use the `ilp-settlement-ethereum` docker image
- Fix manual testnet config docs to use `ilp-settlement-ethereum`
> docs(config, codeowners): fixed to use ilp-settlement-ethereum insted of settlement-engines

- crates/interledger-store/Cargo.toml
- crates/interledger/Cargo.toml
uuid is no longer an optional dep since it's used in the Account struct in the store
Building from the root directory would work, but if you specified `--bin ilp-node` or tried to compile inside the `ilp-node` directory, It'd fail.
> fix(store): make uuid a non-optional dependency

- crates/ilp-node/tests/redis/exchange_rates.rs
- crates/interledger-service-util/src/exchange_rates_service.rs
Closes https://github.com/interledger-rs/interledger-rs/issues/485
IMO it makes more sense to keep things simple and allow only 1 intuitive format, rather than try to support multiple
> fix(exchange-rates-service): remove service provider aliases

- .circleci/config.yml
It seems that building docker images requires over 15min so this PR increases it to 30min.
I'm not sure if this is sufficient but I'd like to see whether it goes well with this.
> ci(config.yml): set timeout to 30m

- crates/ilp-node/src/node.rs
- crates/interledger-settlement/src/api/node_api.rs
- crates/interledger-settlement/src/api/test_helpers.rs
- crates/interledger-settlement/src/core/backends_common/redis/mod.rs
- crates/interledger-settlement/src/core/types.rs
- crates/interledger-store/src/redis/mod.rs
As title.
This was removed in https://github.com/interledger-rs/interledger-rs/pull/535. However, the same trait gets consumed by the Settlement Engines. We should not enforce any limitations on the type account id's engine implementers want to use.
> Revive LeftoversStore's AccountId associated type 

- .circleci/config.yml
- crates/ilp-node/src/instrumentation/google_pubsub.rs
- crates/ilp-node/src/instrumentation/metrics.rs
- crates/ilp-node/src/instrumentation/prometheus.rs
- crates/ilp-node/src/instrumentation/trace.rs
- crates/ilp-node/src/lib.rs
- crates/ilp-node/src/main.rs
- crates/ilp-node/tests/redis/redis_tests.rs
- crates/interledger-service/src/lib.rs
This PR should fail. Exponential type blowup each time we're wrapping our services.
All the [wrapping done in `node.rs` ](https://github.com/interledger-rs/interledger-rs/blob/gakonst/15-futures03-node/crates/ilp-node/src/node.rs#L365-L366)is controlled via the feature-flags `monitoring` and `google-pubsub`.
Related: https://github.com/rust-lang/rust/issues/68508
> Revive all features and investigate type length limit error

- crates/ilp-node/src/main.rs
Because the following message looks a bit awkward, I propose this.
```
Could not parse config file `test.yaml`. Error: "Configuration file error configuration file \"test.yaml\" not found"
```
```
$ cargo run test.yaml
Error: mapping values are not allowed in this context at line 1 column 6 in test.yaml
```
```
$ cargo run test2.yaml
Error: configuration file "test2.yaml" not found
```
> fix(main.rs): to output proper error messages when wrong configs are given

- crates/ilp-node/src/main.rs
Closes https://github.com/interledger-rs/interledger-rs/issues/425
Instead of panic'ing it simply returns an error now. If it's the error where the parser tried to use `ilp-node` as a config file, it instructs the user to use one of the other commands.
> Fix node panic

- Cargo.lock
- crates/ilp-cli/Cargo.toml
- crates/ilp-node/Cargo.toml
- crates/interledger-api/Cargo.toml
- crates/interledger-btp/Cargo.toml
- crates/interledger-btp/src/errors.rs
- crates/interledger-ccp/Cargo.toml
- crates/interledger-ccp/src/packet.rs
- crates/interledger-errors/Cargo.toml
- crates/interledger-http/Cargo.toml
- crates/interledger-ildcp/Cargo.toml
- crates/interledger-packet/Cargo.toml
- crates/interledger-packet/src/address.rs
- crates/interledger-packet/src/errors.rs
- crates/interledger-router/Cargo.toml
- crates/interledger-service-util/Cargo.toml
- crates/interledger-service/Cargo.toml
- crates/interledger-settlement/Cargo.toml
- crates/interledger-spsp/Cargo.toml
- crates/interledger-spsp/src/lib.rs
- crates/interledger-store/Cargo.toml
- crates/interledger-stream/Cargo.toml
- crates/interledger-stream/src/error.rs
This commit removes some entirely unused dependencies, adds `default-features = false` for all dependencies, and replaces all uses of quick-error and failure with thiserror.
As a result, `cargo check` now builds 232 packages (down from 320), `cargo check --all-features` builds 314 (down from 368), and `cargo test --all-features` builds 372 (down from 413).
Consequently a clean build from scratch now takes 2m16s (down from 2m36s).
Fixes #140.
> refactor: prune dependencies

- crates/interledger-api/src/routes/accounts.rs
- crates/interledger-stream/src/client.rs
- crates/interledger-stream/src/congestion.rs
- docs/api.yml
- Fix #513: Compute minimum source amount necessary to deliver money, corresponding to the minimum destination amount. This enables STREAM payments across peers in which a credit limit is hit and settlement occurs during the payment. Previously, T04s would reduce the source amount to 1, which will always fail due to rounding or not meeting the minimum exchange rate.
- Fix #634: Distribute dust amounts across remaining packets. By chance, the last packet in a STREAM payment may be too small that it won't meet the minimum destination amount due to rounding errors. This heuristic approximates in advance if this may happen and increases each packet amount slightly so there's no dust amount.
- Fix #633: Only apply T00, T01, F99 to fail-fast behavior. e.g. T04s should not trigger the fail-fast …
> STREAM sender reliability improvements

- Cargo.lock
- crates/ilp-node/tests/redis/test_helpers.rs
- crates/interledger-packet/src/address.rs
- crates/interledger-stream/src/client.rs
Method description is deprecated since Rust version 1.42.0, mentioned in [Rust docs](https://doc.rust-lang.org/std/error/trait.Error.html#method.description) and also [CircleCI](https://circleci.com/gh/interledger-rs/interledger-rs/4479?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) build fails because of this deprecation.
> Replace deprecated description with Display impl

- crates/interledger-api/src/routes/accounts.rs
- crates/interledger-api/src/routes/node_settings.rs
- crates/interledger-http/Cargo.toml
- crates/interledger-http/src/server.rs
- crates/interledger-settlement/src/api/node_api.rs
- crates/interledger-settlement/src/core/engines_api.rs
- fix the individual build of the `interledger-http` crate that currently fails due to `secrecy::SecretString` requiring the `alloc` feature
- remove calls to `.boxed()` where it is of no consequence to the return values of functions; they introduce extra indirection via `Arc`
> make interledger-http build individually; remove unneeded calls to warp::Filter::boxed

- crates/interledger-api/src/routes/accounts.rs
- crates/interledger-http/src/client.rs
- crates/interledger-packet/src/packet.rs
- crates/interledger-spsp/src/client.rs
- crates/interledger-store/src/redis/reconnect.rs
- crates/interledger-stream/src/client.rs
- crates/interledger-stream/src/lib.rs
- crates/interledger-stream/src/packet.rs
These changes mostly target unnecessary allocations; individual commits describe specific changes.
In [one case](https://github.com/interledger-rs/interledger-rs/commit/4b76734e98a9f80419186b67cb871a38448fe3e6) I changed the `TODO` to `FIXME`, because it's a bit of a liability; it can be easily fixed, but doing so requires 2 related tests to be adjusted:
```
---- balances_test::prepare_then_fulfill_with_settlement stdout ----
thread 'balances_test::prepare_then_fulfill_with_settlement' panicked at 'assertion failed: `(left == right)`
left: `"No such file or directory (os error 2)"`,
right: `"Broken pipe (os error 32)"`', crates/interledger-store/tests/redis/balances_test.rs:197:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
---- …
```
> Squash a few perf-related TODOs

- crates/interledger-router/src/router.rs
- crates/interledger-settlement/src/core/settlement_client.rs
It seems that CI pulls the most recent stable; fix the new clippies it introduces.
Unblocks #647, #649 and any other PR really :stuck_out_tongue:.
> fix: adjust code for 1.44 clippies

- crates/ilp-node/Cargo.toml
- crates/ilp-node/src/main.rs
- crates/ilp-node/src/node.rs
- crates/ilp-node/src/redis_store.rs
- crates/ilp-node/tests/redis/btp.rs
- crates/ilp-node/tests/redis/exchange_rates.rs
- crates/ilp-node/tests/redis/prometheus.rs
- crates/ilp-node/tests/redis/three_nodes.rs
This solution improves the current logging/tracing setup by setting it up earlier, fixing the runtime log level control (it no longer resets the non-default settings) and allowing for multiple log subscribers (currently just `stdout`).
This change can be later extended with additional log subscribers including channels, websockets, log files etc.
> Enhanced tracing setup

- README.md
Add Apache 2.0 License badge in README.MD. #158
> add Apache license badge in readme

- crates/ilp-node/src/node.rs
- crates/interledger-http/src/server.rs
Address a bit of #615 by removing 2 unnecessary allocations of the incoming service.
> perf: remove a few clones of the incoming service chain

- crates/interledger-api/Cargo.toml
- crates/interledger-api/src/routes/accounts.rs
There is a potential problem with websocket paths in accounts API:
`/accounts/:username/payments/incoming` &
`/payments/incoming`.
The server is not consuming any messages from the client, and in that case it is not returning pong responses to the client. It appears that `warp` is not sending appropriate pong responses if the messages are not consumed. 
The fix proposed in this PR is adding a loop that consumes all received messages in to order enable server to return appropriate pong responses. This helps with a potential `keep-alive` from the clients that send periodic ping requests and expect an appropriate pong response.
I have used `tokio` tasks, and moved tokio as a dep because I have seen it used across the repo. If that is a problem, maybe we could consider a solution based on …
> Consume messages in websockets to unlock pong responses

- Cargo.lock
- crates/ilp-node/Cargo.toml
- crates/interledger-api/Cargo.toml
- crates/interledger-btp/Cargo.toml
- crates/interledger-ccp/Cargo.toml
- crates/interledger-http/Cargo.toml
- crates/interledger-ildcp/Cargo.toml
- crates/interledger-rates/Cargo.toml
- crates/interledger-service-util/Cargo.toml
- crates/interledger-service/Cargo.toml
- crates/interledger-settlement/Cargo.toml
- crates/interledger-spsp/Cargo.toml
- crates/interledger-store/Cargo.toml
- crates/interledger-stream/Cargo.toml
CircleCI audit check fails: `cargo audit --ignore RUSTSEC-2019-0031 --ignore RUSTSEC-2020-0041 --ignore RUSTSEC-2020-0016`.
Fix is to bump `futures` version to `0.3.7`
> Bump futures version to please the audit

- Cargo.lock
- crates/interledger-store/src/redis/mod.rs
In the current code only the last consumer that subscribes to `/accounts/:username/payments/incoming` will get notifications. The quick fix is store a vec of `UnboundedSender` per accountID instead of a single one.
The goal was to support a several clients per accountID. If we expect much more clients per accountID in the future,  more scalable solution could be considered.
> Allow multple consumers per accountID in websocket payment subcription

- crates/interledger-stream/Cargo.toml
Cargo.toml in the `interledger-stream` package was missing the feature `"std"` for `base64`. This caused it to report an error when building or testing the package in isolation. This pull request introduces the minor fix to the problem.
> Fix interledger-stream build and test in isolation

- Cargo.lock
Another separated from #644: minimum updates while there are many others which could be done as well.
> chore: update arc-swap following RUSTSEC-2020-0091

- crates/ilp-node/src/main.rs
- crates/ilp-node/src/node.rs
- crates/ilp-node/tests/redis/redis_tests.rs
- crates/ilp-node/tests/redis/time_based_settlement.rs
- crates/interledger-api/src/routes/test_helpers.rs
- crates/interledger-service-util/src/balance_service.rs
- crates/interledger-service-util/src/lib.rs
- crates/interledger-settlement/src/core/engines_api.rs
- crates/interledger-store/src/redis/lua/process_settle.lua
- crates/interledger-store/src/redis/mod.rs
Currently interledger-rs supports settling peer accounts whenever their balance goes over `settle_threshold`, settling for `balance - settle_to` and thus resetting the `balance` to `settle_to`. This PR adds a time-based method which works in addition to the existing threshold-based settlement. This feature allows driving the balance to `settle_to` later. The feature works with  `settle_threshold`: if the balance goes over the threshold, a settlement is still fired off right away and any existing time-based settlement is cancelled.
The feature works by adding a delay on each prepare for every peering account id which did not already have a delay. The delay duration is set through the `--settle_every` configuration option. When the delay expires, a path similar to threshold settlement is …
> Add time-based settlement to complement the threshold-based

- crates/ilp-node/src/main.rs
- crates/ilp-node/src/node.rs
- crates/ilp-node/src/redis_store.rs
- crates/ilp-node/tests/redis/payments_incoming.rs
- crates/interledger-store/src/redis/lua/account_from_username.lua
- crates/interledger-store/src/redis/lua/load_accounts.lua
- crates/interledger-store/src/redis/lua/process_fulfill.lua
- crates/interledger-store/src/redis/lua/process_incoming_settlement.lua
- crates/interledger-store/src/redis/lua/process_prepare.lua
- crates/interledger-store/src/redis/lua/process_reject.lua
- crates/interledger-store/src/redis/lua/process_settle.lua
- crates/interledger-store/src/redis/lua/refund_settlement.lua
- crates/interledger-store/src/redis/mod.rs
The main use case to cover was to enable nodes to share the same redis db instance without braking the existing functionality. The proposed solution was to use different prefix for each node that want to share the db instance. This PR is enabling use of prefix, if provided, for redis in all db calls so that this functionality can be achieved. 
I have tested the functionality by running the examples from the `/examples` folder, and by  subscribing to various nodes with ws client to check the redis pub/sub as well.
With 2 nodes started, 1st one (node_a) without a prefix and a second one (node_b) with `test` prefix like: 
```
cargo run --bin ilp-node -- --ilp_address example.node_b \                                                                
--secret_seed …
```
> Enable multiple nodes to use same redis db

- .circleci/config.yml
- Cargo.lock
- crates/interledger-api/src/routes/node_settings.rs
- crates/interledger-btp/src/packet.rs
- crates/interledger-ccp/src/routing_table.rs
- crates/interledger-ccp/src/test_helpers.rs
- crates/interledger-packet/src/address.rs
- crates/interledger-rates/src/cryptocompare.rs
- crates/interledger-router/src/router.rs
- crates/interledger-settlement/src/core/types.rs
- crates/interledger-store/src/crypto.rs
- crates/interledger-store/src/redis/mod.rs
- crates/interledger-store/tests/redis/accounts_test.rs
- crates/interledger-stream/src/lib.rs
- crates/interledger-stream/src/server.rs
`cargo clippy` and `cargo audit` have some new warnings since the new version. This is an attempt to simply fix those.
> Fix clippy and audit warnings

- .circleci/config.yml
This is an addition to #667. I did not know that `medium+` instances are also going to break, and it happened on release related tasks.
> Reduce resourse class for all actions as well

- crates/ilp-node/tests/redis/payments_incoming.rs
- crates/interledger-stream/src/server.rs
- docs/api.md
For improved payment tracking and debugging, we'd like to add two additional fields to the WebSocket payment notifications: the Boolean value `connection_closed` and the packet sequence number `sequence`.
The `connection_closed` field will be `true` only when the last packet, which contains the `ConnectionClose` frame, has been received. As a result, in addition to the normal payment notifications reported in the WebSocket, an extra notification will be sent at the end, containing `{ "amount": 0, "connection_closed": true, ... }`.
The `sequence` field reports the sequence number of each received payment-carrying packet.
> Add fields to WebSocket notifications

- .circleci/config.yml
- .github/workflows/ci.yml
- .github/workflows/test-md.yml
This PR is switching `build` and `test-md` steps from circleci to github actions. These steps are run on pushes and PRs.
The release part is deprecated since it is not suppored by the current plan, and it will be switched to gh actions in the separate PR.
Part of #669.
> Switch from circleCI to github actions

- .github/workflows/docker.yml
Docker releases that mimic the same behavior as before. Docker releases are triggered on:
- push to master
- tag on any branch with `ilp-node-|ilp-cli-` prefix
Tag is derived same as before, using the same scripts.
This is only the dry-run and will not push images to dockerhub.
> Docker releases on gh actions

- .github/workflows/docker.yml
Fix a image tag parsing in the case of a merge to `master` branch
> Fix image tag parsing in gh actions docker script

- .github/workflows/docker.yml
This PR will enable the docker push in docker release gh action job. 
CAUTION: this will fix the broken docker push at the moment and TRIGGER docker build & push of the latest `ilp-node`, `ilp-cli` & `testnet` images.
Cc #669 
Cc: #678
> Enable push in docker release job

- Cargo.lock
- crates/ilp-node/Cargo.toml
- crates/ilp-node/src/instrumentation/google_pubsub.rs
- crates/ilp-node/src/node.rs
Take 2 of #682. Closes #682. This updates `yup-oauth2 = "4"`, which removes the need for hyper 0.12 in the dependency tree, while also updating the hyper 0.13 version. Sadly there are doesn't seem to be any tests for the google pubsub functionality so we can only hope it continues to work. Last commit updates rest of the dependencies.
> Update dependencies following RUSTSEC-2021-0020

- Cargo.lock
Fixes the latest CI failure following [RUSTSEC-2021-0023](https://rustsec.org/advisories/RUSTSEC-2021-0023.html).
> chore(deps): bump rand_core 0.6 to 0.6.2

- Cargo.lock
- crates/ilp-node/Cargo.toml
- crates/ilp-node/README.md
- crates/ilp-node/benches/multiple_payments.rs
- crates/ilp-node/benches/redis_helpers.rs
- crates/ilp-node/benches/test_helpers.rs
Adds two benchmarks which tracks, how long it takes for an ilp-node to receive payment through websocket, process it and respond back. One benchmark with high packet count and one benchmark with lower packet count.
```bash #
cargo bench -- process_payment
```
> Multiple payments benchmark

- README.md
- crates/ilp-node/benches/redis_helpers.rs
- crates/ilp-node/tests/redis/redis_helpers.rs
- crates/interledger-btp/src/packet.rs
- crates/interledger-ccp/src/packet.rs
- crates/interledger-ccp/src/server.rs
- crates/interledger-packet/src/oer.rs
- crates/interledger-packet/src/packet.rs
- crates/interledger-settlement/src/core/backends_common/redis/test_helpers/redis_helpers.rs
- crates/interledger-store/tests/redis/redis_tests.rs
- crates/interledger-stream/src/client.rs
- crates/interledger-stream/src/crypto.rs
- crates/interledger-stream/src/packet.rs
- crates/interledger-stream/src/server.rs
- 2021 edition lints re: panic
- 1.51 redundant_slicing
- needless_question_mark
> chore(*): clippy 1.51 lints

- .github/workflows/docker.yml
- docker/Dockerfile
- docker/ilp-cli.dockerfile
- docker/ilp-node.dockerfile
When doing #680 I didn't notice the docker build failure and have been figuring out how to fix it since. Looking more closely to the dockerfile it already uses a two container construction so I was able to identify the issue being "only parts of the working copy are copied into the build container". The fix is obvious in hindsight.
Fixes #694 but we will not know until I merge this into master, we should have a third workflow which depends on both `build` and `test-md` and attempts to build the docker images.
> fix(docker): make .git available for the build image

- .github/workflows/ci.yml
- scripts/parse-md.sh
- scripts/run-md-test.sh
- scripts/run-md.sh
Separated from #693 which had a tough evening yesterday with multiple consecutive failures before starting to work again. This fixes:
- the `test-md` logs (artifacts) are now only uploaded on failure (was only on success)
- limiting the workflow execution to only pull requests and master branch (will allow anyone contributing with spam)
- `rm` failure is from the bogus `~/.interledger` deletion which I do not know the reason for
- it should probably be removed altogether
- I have no idea what was the original point nor do I consider these scripts safe to run locally because of things like these
- refactor the "mdlp" out to a simple to use awk wrapper with help, for the next time one needs to decipher the README.mds
> CI and test-md enhancements

- crates/ilp-node/tests/redis/exchange_rates.rs
- scripts/run-md.sh
The coinbase test was flaky, and it started completely failing once coinbase suspended `XRP`. To avoid this in the future and to allow for coinbase to suspend some rates and not break our tests, I have added a simple logic to pass the test if 70% of related asserts were true.
> Reduce the amount of asserts in coinbase test to make it less flaky

- crates/ilp-node/src/node.rs
- crates/interledger-stream/src/crypto.rs
- crates/interledger-stream/src/packet.rs
- crates/interledger-stream/src/server.rs
First commit has more of a "drive-by" refactoring, but the rest are related to the case. It turns out that the "Error decrypting Unspecified" is totally worthless `error!` level message, because:
* when separating the F06 path and the F99 paths in 842268f it becomes apparent that the error message is only related to F06
* so it can be removed in c709c94 
* and the `send_request` impl can be simplified not to have any fallthrough in 5e98c4d
Specifically this removes two log messages:
1. ["Error decrypting Unspecified"](https://github.com/interledger-rs/interledger-rs/blob/33055529c888f64a08fdbf12addcd23ea1bac7d3/crates/interledger-stream/src/crypto.rs#L172) (always formatted but same  string)
2. ["Unable to parse data, rejecting Prepare …
> Remove error decrypting unspecified

- crates/interledger-packet/src/packet.rs
Cc: #705 
Check if bytes are numerical values before handing to chrono
> fix(packet): add precheck for timestamps in Prepares

- crates/interledger-packet/fuzz/Cargo.toml
- crates/interledger-packet/src/packet.rs
cc: #705 
Trailing bytes with length included in the varlen octet string that do not contribute to the data field should not be allowed.
> disallow extra trailing bytes in Fulfillment packet

- crates/interledger-store/src/redis/mod.rs
- crates/interledger-store/tests/redis/notifications.rs
Fixes #711. Adds synchronization for the launched thread, and retry for the test case.
> Fix test flakyness

- Cargo.lock
- crates/interledger-rates/Cargo.toml
- crates/interledger-stream/Cargo.toml
- crates/interledger-stream/src/congestion.rs
This removes the csv dump functionality from `interledger-stream` which is enabled on all test runs thanks to `--all-features`. The 6e5b804 should be reverted if this dev feature is found being needed later on.
Removal of `async-trait` in `interledger-rates` is a drive-by cleanup motivated by `cargo udeps` finding it.
> Limit csv output in ci logs

- crates/interledger-service-util/src/exchange_rates_service.rs
- crates/interledger-settlement/src/core/types.rs
normalize_scale had previously some conversion problems as there was a conversion from u8 to i8. This also makes one ignored test; named calculates_with_high_asset_scale; work.
> fix and clean f64's normalize_scale function

- .github/workflows/ci.yml
I had forgotten to do this a while ago, when introducing the `interledger-packet/strict` feature.
> ci: add testing of without and with strict feats

- crates/interledger-stream/fuzz/Cargo.toml
- crates/interledger-stream/src/packet.rs
cc: #705 
Focused on fuzzing `StreamPacket`
- when parsing of stream packet data into valid known frames errors, it is returned instead of ignored
- updated a fuzz test name for clarification of cause of failure
- added new test and code for removing trailer bytes for fuzzing
TODO: 
- add new test and handle Unknown frames for fuzzing
> Stream fuzzing fixes

- .github/workflows/ci.yml
- crates/interledger-stream/Cargo.toml
- crates/interledger-stream/fuzz/Cargo.toml
- crates/interledger-stream/src/lib.rs
- crates/interledger-stream/src/packet.rs
cc: #705 
This PR addresses:
- ensures no inner trailing bytes in frame data
- adds roundtrip-only feature for fuzzing in the case of saturated value replacement 
- stores and return Unknown ErrorCode and FrameTypes
> stream: Allow fuzzing for Unknown Data (ErrorCode and FrameType)

- crates/interledger-packet/src/error.rs
- crates/interledger-packet/src/packet.rs
Found this crash stashed away, which wasn't because of ErrorCode or parsing, but because of too strict fuzz_target. This PR fixes:
- allow only IA5String (ascii) error codes as is in the ASN.1 definition
- handle debug and display output for the error codes with control characters gracefully
- remove string allocation in ErrorCode's Debug impl
There's some churn related to the roundtrip test fn being added and removed, but I'll follow up with a better `fuzz/fuzz_targets/packet.rs` after this PR.
Cc: #705
> Fix interledger-packet::ErrorCode too lenient parsing

- .github/workflows/ci.yml
- crates/interledger-packet/Cargo.toml
- crates/interledger-packet/fuzz/Cargo.toml
- crates/interledger-packet/fuzz/fuzz_targets/packet.rs
- crates/interledger-packet/src/hex.rs
- crates/interledger-packet/src/lib.rs
- crates/interledger-packet/src/packet.rs
Cc: #705
This is a follow-up to #716 with:
- `interledger-packet/roundtrip-only` feature for denying ILP timestamps which don't roundtrip [^1]
- rejects trailing bytes on `interledger-packet/strict` for Prepare and Reject (continues #710 which did this for Fulfill) [^2]
- stylistic refactoring around unifying the style (assert_eq order, `.to_string()` calls, `if cfg!(...) { } else { }`)
- moves the fuzz target verification to `src/lib.rs` where it can be used with tests as well
- adds `PartialEq` derivation for `interledger-packet::hex::HexString` for use in `assert_eq!(HexString(...), HexString(...));`
[^1]: Unsure if this should be the default; it'd seem that the `60` as the `%S` field is accepted for every date, which might not match the idea in the RFCs. "Every date" as in best to my …
> Continued interledger-packet fuzzability

- crates/interledger-btp/src/errors.rs
- crates/interledger-btp/src/packet.rs
- crates/interledger-ccp/src/packet.rs
- crates/interledger-packet/src/address.rs
- crates/interledger-packet/src/errors.rs
- crates/interledger-packet/src/lib.rs
- crates/interledger-packet/src/packet.rs
- crates/interledger-store/src/account.rs
- crates/interledger-stream/src/client.rs
- crates/interledger-stream/src/error.rs
- crates/interledger-stream/src/lib.rs
- crates/interledger-stream/src/packet.rs
cc #708 
This attempts to decouple the error type `ParseError` in interledger-packet with other crates. 
The idea is to have more explicit errors that are more efficient.
> fix: Clean up and decouple interledge-packet::ParseError in other crates 

- crates/interledger-http/src/client.rs
- crates/interledger-http/src/lib.rs
- crates/interledger-service-util/src/balance_service.rs
- crates/interledger-service-util/src/rate_limit_service.rs
fixed [bool_assert_comparison](https://rust-lang.github.io/rust-clippy/master/index.html#bool_assert_comparison) and [from_iter_instead_of_collect](https://rust-lang.github.io/rust-clippy/master/index.html#from_iter_instead_of_collect) clippy lint warnings.
> Clippy warnings in 1.53

- crates/ilp-node/Cargo.toml
This PR adds `features = ["v4"]` to `crates/ilp-node/Cargo.toml` to prevent a confusing error that might occur when trying to use i.e. `Uuid::new_v4` downstream.
> fix(ilp-node): explicit use of uuid v4 feature

- .github/workflows/ci.yml
- scripts/run-md-test.sh
This PR adds dependency caching to the CI workflow, dramatically speeding up builds (after the first one). Note: does not include the docker workflow -- may be of interest too (?) but I'm not sure how it could work.
Also adds `workflow_dispatch` trigger, which will let us manually trigger the workflow. Mainly useful for testing on forks without having to fiddle with the workflow file.
Uses the [rust-cache action](https://github.com/Swatinem/rust-cache). We could try manually figure out which parts of `/target` to cache, but I found it difficult and prone to error. This action seems to do the right thing and ends up caching about 2 GB total with the way I have it setup (multiple jobs, with independent caches).
It may be possible to further optimize the cache by sharing amongst the jobs, …
> CI speedup

- .github/workflows/ci.yml
- .github/workflows/commits.yml
- docs/CONTRIBUTING.md
This PR introduces a new github workflow which ensures all commits in a PR conform to our requirements. It checks for the following:
1. conventional commit messages
2. used `git commit --signoff`
3. no extra merge commits
The first two points are taken care of by the NPM [`commitlint`](https://github.com/conventional-changelog/commitlint) package. Unfortunately, they provide guides for CircleCI and TravisCI but not for Github Actions ([open issue](https://github.com/conventional-changelog/commitlint/issues/586)). I managed to get it working after some trial and error. 
There is a 3rd party Github Action which looks great, but unfortunately I ran into [this bug](https://github.com/wagoid/commitlint-github-action/issues/187). It also seemed like a lot of code to audit, considering we don't …
> ci: add commit checks for PRs

- .github/workflows/ci.yml
- Cargo.lock
- crates/ilp-cli/src/interpreter.rs
- crates/interledger-http/src/lib.rs
- crates/interledger-service/src/lib.rs
1) Upgrades pin-project and crossbeam-deque dependencies to clear a clippy errors
2) Handles unused variables
3) Adds more cargo audit ignores
> Chore: Fix CI errors
