.gitignore, crates/interledger-http/src/client.rs
Signed-off-by: sappenin <sappenin@gmail.com>
=> Fix Ilp-over-Http Content-Type

LICENSE, README.md, docs/CONTRIBUTING.md
- Add LICENSE and CONTRIBUTING.md
- Previous discussions are here: https://github.com/emschwartz/interledger-rs/pull/64
=> Add LICENSE and CONTRIBUTING.md

.gitignore, crates/interledger-service-util/Cargo.toml, crates/interledger-service-util/src/echo.rs, crates/interledger-service-util/src/lib.rs, docs/architecture.md
Though this is WIP (and actually not working), you might be able to confirm the base implementation.
If you have any opinion so far, could you comment here?
=> Add echo service

crates/interledger-btp/src/lib.rs, crates/interledger-btp/src/service.rs, crates/interledger-ccp/src/packet.rs, crates/interledger-ccp/src/server.rs, crates/interledger-ccp/src/test_helpers.rs, crates/interledger-http/src/client.rs, crates/interledger-http/src/server.rs, crates/interledger-ildcp/src/packet.rs, crates/interledger-packet/src/address.rs, crates/interledger-packet/src/errors.rs, crates/interledger-packet/src/fixtures.rs, crates/interledger-packet/src/packet.rs, crates/interledger-router/src/router.rs, crates/interledger-service-util/src/max_packet_amount.rs, crates/interledger-service-util/src/rates_and_balances.rs, crates/interledger-service-util/src/validator.rs, crates/interledger-stream/src/client.rs, crates/interledger-stream/src/congestion.rs, crates/interledger-stream/src/lib.rs, crates/interledger-stream/src/packet.rs, crates/interledger-stream/src/server.rs, crates/interledger/src/cli.rs
Stacked PR on top of #75, should be merged on it, and then we merge to master.
=> Use IlpAddress in rest of codebase and fix tests

crates/interledger-btp/src/service.rs, crates/interledger-ccp/src/server.rs, crates/interledger-http/src/client.rs, crates/interledger-ildcp/src/server.rs, crates/interledger-service-util/src/balance_service.rs, crates/interledger-service-util/src/echo_service.rs, crates/interledger-settlement/src/message_service.rs, crates/interledger-stream/src/server.rs
=> Rename Generics for consistency

.circleci/config.yml, README.md, crates/interledger-btp/src/service.rs, n
The BTP change fixes the issue that was causing panics in this run: https://circleci.com/gh/emschwartz/interledger-rs/511
=> Minor CI fixes

crates/interledger-api/README.md, crates/interledger-btp/README.md, crates/interledger-ccp/README.md, crates/interledger-http/README.md, crates/interledger-ildcp/README.md, crates/interledger-packet/README.md, crates/interledger-service/README.md, crates/interledger-spsp/README.md, crates/interledger-store-memory/README.md, crates/interledger-stream/README.md, crates/interledger/README.md
Cobbled together from a combination of crate-level comments and excerpts from personal notes. Please review each one for accuracy since I don't have a lot of firsthand experience with these crates yet myself. :)
=> Add minimal READMEs for the individual crates in the repo

crates/interledger-settlement-engines/src/api.rs, crates/interledger-settlement-engines/src/engines/ethereum_ledger/eth_engine.rs, crates/interledger-settlement-engines/src/stores/redis_ethereum_ledger/store.rs, crates/interledger-settlement-engines/tests/eth_ledger_settlement.rs, crates/interledger-settlement-engines/tests/eth_xrp_interoperable.rs, crates/interledger-settlement-engines/tests/test_helpers.rs, crates/interledger-settlement-engines/tests/xrp_ledger_settlement.rs, crates/interledger-settlement/src/api.rs, crates/interledger-settlement/src/client.rs, crates/interledger-settlement/src/message_service.rs, examples/charlie.yaml, examples/eth-settlement/settlements_test.sh, examples/eth_xrp_three_nodes/README.md, examples/eth_xrp_three_nodes/interoperable.sh, examples/pay_dump.sh
=> XRP - ETH 3 Node E2E Test + Settlement

.circleci/config.yml, crates/interledger-settlement-engines/src/api.rs, crates/interledger-settlement-engines/src/engines/ethereum_ledger/eth_engine.rs, crates/interledger-settlement-engines/src/stores/redis_ethereum_ledger/store.rs, crates/interledger-settlement-engines/tests/eth_ledger_settlement.rs, crates/interledger-settlement-engines/tests/eth_xrp_interoperable.rs, crates/interledger-settlement-engines/tests/redis_helpers.rs, crates/interledger-settlement-engines/tests/test_helpers.rs, crates/interledger-settlement-engines/tests/xrp_ledger_settlement.rs, crates/interledger-settlement/src/api.rs, crates/interledger-settlement/src/client.rs, examples/charlie.yaml, examples/eth-settlement/README.md, examples/eth-settlement/settlements_test.sh, examples/eth_xrp_three_nodes/README.md, examples/eth_xrp_three_nodes/interoperable.sh, examples/pay_dump.sh, examples/xrp_ledger/README.md, examples/xrp_ledger/xrp_settlements_test.sh
- Installs https://github.com/interledgerjs/settlement-xrp/ to Circle
- Runs Rust e2e test illustrating settlement working
- Adds README and shell scripts for reproducing from the user side
=> XRP Engine E2E Test

crates/interledger/tests/three_nodes.rs
The three_nodes test on closer inspection is flaky. The packet does not get fulfilled properly for some reason.
CI: https://circleci.com/gh/emschwartz/interledger-rs/tree/flaky-e2e-test
Locally run logs:
```
Running /Users/gakonst/projects/xpring-contract/interledger-rs/target/debug/deps/three_nodes-8287d071321a8ac7
running 1 test
[2019-08-01T18:04:42Z DEBUG interledger_store_redis::store] Connected to redis: Client { connection_info: ConnectionInfo { addr: Unix("/tmp/redis-rs-test-5605630314541309643-1743366804601776152.sock"), db: 2, passwd: None } }
[2019-08-01T18:04:42Z DEBUG interledger_store_redis::store] Connected to redis: Client { connection_info: ConnectionInfo { addr: Unix("/tmp/redis-rs-test-5605630314541309643-1743366804601776152.sock"), db: 1, passwd: None } } …
```
=> Flaky 3 nodes test

examples/README.md
=> docs(example/readme.md): fixed a wrong link

crates/interledger-api/src/lib.rs, crates/interledger-service-util/src/expiry_shortener_service.rs, crates/interledger-store-redis/src/account.rs, crates/interledger/src/main.rs
=> Enforce maximum expiry duration

crates/interledger-settlement-engines/Cargo.toml, crates/interledger-settlement-engines/src/engines/ethereum_ledger/eth_engine.rs, crates/interledger-settlement-engines/src/engines/ethereum_ledger/types.rs, crates/interledger-settlement-engines/src/main.rs, crates/interledger-settlement-engines/tests/eth_engine_integration_tests/ganache_tests.rs, crates/interledger-settlement-engines/tests/test_helpers.rs, crates/interledger-store-redis/Cargo.toml, crates/interledger-store-redis/README.md, crates/interledger-store-redis/src/account.rs, crates/interledger-store-redis/src/crypto.rs, crates/interledger-store-redis/src/store.rs
=> Hide secrets

README.md
Its the same repository, just for consistency.
=> Rename to new path

.github/config.yml
This enables the [Commit Message Lint](https://github.com/SystangoTechnologies/commit-message-lint/wiki/Commit-Message-Lint---2.0?installation_id=1812861&setup_action=install) app
=> Enforce commit message style

crates/interledger-ccp/src/server.rs, crates/interledger-ccp/src/test_helpers.rs
Came up in #248:
https://github.com/interledger-rs/interledger-rs/issues/248#issuecomment-528623430
=> Do not spawn tasks via conditional compilation instead of boolean

crates/interledger-api/src/lib.rs, crates/interledger-api/src/routes/accounts.rs, crates/interledger-store-redis/src/store.rs, crates/interledger-store-redis/tests/accounts_test.rs
=> Modify Account Settings

.github/config.yml, docs/CONTRIBUTING.md
=> docs: document some useful git hooks

docs/api.md
=> docs(api docs): add settlement_engine_url

README.md
Minor modifications to README headers.
=> Fix readme headers

crates/ilp-node/src/node.rs, crates/ilp-node/tests/btp.rs, crates/interledger-api/Cargo.toml, crates/interledger-api/src/http_retry.rs, crates/interledger-api/src/lib.rs, crates/interledger-api/src/routes/accounts.rs, crates/interledger-api/src/routes/node_settings.rs, crates/interledger-btp/src/server.rs, crates/interledger-btp/src/service.rs, crates/interledger-ccp/src/server.rs, crates/interledger-packet/src/address.rs, crates/interledger-router/src/router.rs, crates/interledger-service/src/auth/username.rs, crates/interledger-service/src/lib.rs, crates/interledger-settlement-engines/src/stores/redis_ethereum_ledger/store.rs, crates/interledger-settlement-engines/tests/eth_xrp_interoperable.rs, crates/interledger-settlement-engines/tests/test_helpers/mod.rs, crates/interledger-store-redis/src/store.rs, crates/interledger-store-redis/tests/accounts_test.rs, crates/interledger-store-redis/tests/common/fixtures.rs, crates/interledger-store-redis/tests/settlement_test.rs, crates/interledger-stream/src/client.rs, crates/interledger-stream/src/server.rs, docs/api.md
Resolves https://github.com/interledger-rs/interledger-rs/issues/337
Resolves #178 
This also includes various fixes related to BTP, CCP, and dynamically setting the ILP address based on the ILDCP response from the parent.
=> Node-wide settlement engine url map + various fixes

crates/ilp-node/tests/three_nodes.rs, crates/interledger-ccp/src/routing_table.rs, crates/interledger-ccp/src/server.rs, crates/interledger-router/src/router.rs, crates/interledger-service/src/auth/username.rs, crates/interledger-store-redis/src/account.rs, crates/interledger-store-redis/src/store.rs
This test was flaky, we went through a few rounds of ideas, ended up modifying the test to avoid race conditions altogether.
=> Make Three Nodes test work reliably

crates/interledger-settlement-engines/src/engines/ethereum_ledger/eth_engine.rs, crates/interledger-settlement-engines/src/engines/ethereum_ledger/test_helpers/utils.rs, crates/interledger-settlement-engines/src/engines/ethereum_ledger/types.rs, crates/interledger-settlement-engines/src/stores/redis_ethereum_ledger/store.rs, crates/interledger-settlement-engines/tests/eth_engine_integration_tests/utils.rs
Otherwise we may spam our ethereum node, and we do not want that. Should fix https://github.com/interledger-rs/interledger-rs/issues/353
=> Namespace block numbers

crates/interledger-settlement-engines/src/engines/ethereum_ledger/eth_engine.rs
The eth_estimateGas call fails on geth because geth does not comply to the json-rpc spec. We add a default gas amount instead
=> fix(eth-engine): Use default gas amount if estimateGas call fails

crates/interledger-api/src/lib.rs, crates/interledger-api/src/routes/accounts.rs, crates/interledger-ccp/src/server.rs, crates/interledger-http/src/client.rs, crates/interledger-settlement-engines/tests/eth_xrp_interoperable.rs, crates/interledger-settlement-engines/tests/test_helpers/mod.rs, crates/interledger-settlement-engines/tests/xrp_ledger_settlement.rs, crates/interledger-store-redis/src/lib.rs, crates/interledger-store-redis/src/reconnect.rs, crates/interledger-store-redis/src/store.rs, crates/interledger-store-redis/tests/routing_test.rs
Resolves https://github.com/interledger-rs/interledger-rs/issues/332
Partially implements https://github.com/interledger-rs/interledger-rs/issues/193 (blocked on an upstream change that's needed to implement it fully)
=> Reliability improvements

crates/ilp-cli/README.md, crates/ilp-cli/src/interpreter.rs
also points to the prod API link
=> ILP CLI Docker Readme

crates/ilp-cli/Cargo.toml, crates/ilp-cli/src/interpreter.rs
We must fix this in the future, just for the hackathon.
=> fix(interpreter.rs): send numbers in JSON

Cargo.lock, crates/ilp-cli/Cargo.toml, crates/ilp-cli/src/interpreter.rs, crates/ilp-cli/src/parser.rs, crates/ilp-node/src/node.rs
I've been awake for 40 hours and have ascended beyond earthly concerns such as code quality
=> feat(ilp-cli): incoming-payments subcommand

crates/interledger-settlement-engines/src/stores/test_helpers/redis_helpers.rs
=> chore(engines): remove extern crate from test helpers

crates/interledger-packet/src/error.rs
Add tests to ensure that all error codes match the RFC
=> Test error codes

examples/eth-settlement/README.md, examples/simple/README.md, examples/xrp-settlement/README.md
Resolves https://github.com/interledger-rs/interledger-rs/issues/404
=> fix: make simple example work when run from any directory

Cargo.lock, crates/ilp-node/Cargo.toml, crates/interledger-store-redis/Cargo.toml, crates/interledger-store-redis/src/reconnect.rs, crates/interledger-store-redis/src/store.rs
=> Finish adding Redis reconnection logic

examples/eth-settlement/README.md, examples/eth-xrp-three-nodes/README.md
=> docs: fix readmes for eth engines now that they are in a separate repo

crates/interledger-stream/src/congestion.rs
Described in #430 , `max_packet_amount` may panic with `subtract overflow` when at one point the max. in flight amount is less than the in-flight amount.
This PR attempts to fix it by adding a checking in the `max_packet_amount` method to return `0` when there is no in-flight "space" available.
=> Fix max_packet_amount subtract overflow error

crates/interledger-store-redis/src/lua/account_from_username.lua, crates/interledger-store-redis/src/lua/load_accounts.lua, crates/interledger-store-redis/src/lua/process_fulfill.lua, crates/interledger-store-redis/src/lua/process_incoming_settlement.lua, crates/interledger-store-redis/src/lua/process_prepare.lua, crates/interledger-store-redis/src/lua/process_reject.lua, crates/interledger-store-redis/src/lua/refund_settlement.lua, crates/interledger-store-redis/src/store.rs
The discussion at https://github.com/interledger-rs/interledger-rs/issues/439 got me thinking about our Lua scripts, and this cleans them up a bit. I did notice that the test suite was printing the same "attempt to concatenate" error message as in https://github.com/interledger-rs/interledger-rs/issues/439 and that this error message disappeared following these commits, so I can't confirm that that issue is fixed but it should at least help us track it down further.
=> Lua tweaks

crates/interledger-settlement/src/api.rs, crates/interledger-settlement/src/lib.rs
required to reuse these errors in the [`settlement-engines` PR ](https://github.com/interledger-rs/settlement-engines/pull/5)
=> chore: expose settlement errors

crates/ilp-node/tests/btp.rs, crates/ilp-node/tests/three_nodes.rs
Regarding #464
Hope this helps a little bit to understand what's happening.
=> chore(node tests): add debug messages

Cargo.lock, Cargo.toml, crates/ilp-node/Cargo.toml, crates/ilp-node/src/lib.rs, crates/ilp-node/src/main.rs, crates/ilp-node/src/metrics.rs, crates/ilp-node/src/node.rs, crates/ilp-node/src/trace.rs, crates/ilp-node/tests/btp.rs, crates/ilp-node/tests/exchange_rates.rs, crates/ilp-node/tests/prometheus.rs, crates/ilp-node/tests/test_helpers.rs, crates/ilp-node/tests/three_nodes.rs, crates/interledger-ccp/src/server.rs, crates/interledger-service/Cargo.toml, crates/interledger-service/src/lib.rs, crates/interledger-service/src/trace.rs, crates/interledger/Cargo.toml
Part of #119 
You can see what the output looks like from the `three_nodes` test:
<details>
<summary>Three Nodes test output with tracing</summary>
**Note**: the interesting lines start with `node1:...`, `node2:...`, etc
```
Running target/debug/deps/three_nodes-693f2509f3face00
running 1 test
Oct 23 19:19:07.393DEBUG interledger-node: Starting Interledger node with ILP address: example.alice
Oct 23 19:19:07.394DEBUG node1: interledger_store_redis::store: Connected subscription client to redis: Client { connection_info: ConnectionInfo { addr: Unix("/tmp/redis-rs-test-11461065457172964687-12583690696295489022.sock"), db: 1, passwd: None } }
Oct 23 19:19:07.395DEBUG interledger-node: Starting Interledger node with ILP address: example.bob
Oct 23 19:19:07.396DEBUG node2: …
```
=> Add tracing for ilp-node

crates/interledger-api/src/routes/node_settings.rs, crates/interledger-api/tests/node_settings.rs, docs/api.md
=> Use usernames for /routes endpoints

Cargo.lock, crates/ilp-cli/Cargo.toml, crates/ilp-node/Cargo.toml, crates/ilp-node/tests/exchange_rates.rs, crates/interledger-api/Cargo.toml, crates/interledger-btp/Cargo.toml, crates/interledger-http/Cargo.toml, crates/interledger-service-util/Cargo.toml, crates/interledger-service-util/src/exchange_rates_service.rs, crates/interledger-settlement/Cargo.toml, crates/interledger-spsp/Cargo.toml
See the commit messages for details
=> Various exchange rate fixes

.circleci/config.yml, crates/ilp-node/tests/three_nodes.rs
To investigate more about #490, fixed some lines to output more detailed information.
I could not reproduce errors on my computer, so I need more information in the CI process.
=> refactor(three_nodes test, .circleci/config.yml): fixed account usernames to be clearer, etc

docs/CONTRIBUTING.md
Tell the developer to run clippy so that their changes don't fail CI.
Signed-off-by: Kevin W Matthews <kevinwmatthews@gmail.com>
=> docs(contributing): add instructions on using clippy

crates/ilp-node/Cargo.toml, crates/ilp-node/src/node.rs
Resolves #159 
I'm not totally sure that this should be a compiler flag (rather than a config parameter on the `InterledgerNode`), but I had problems trying to make the application of a service dependent on a config parameter. The compiler complains that the types returned by the if and else branches don't match.
=> Make balance tracking optional

crates/interledger-service/src/auth/token.rs
Fix: #500
⚠️ Note that procedures of authorization should be entirely refactored once the RFC of `Interledger HTTP Authentication Profiles` by @sappenin is merged, considering also #357.
Formerly, some parts of outgoing tokens are discarded unexpectedly. For example, if we parse an
outgoing token of `interledger:rust:test`, it had been sent as `interledger:rust`. This fixes to
send it as `interledger:rust:test`.
=> fix(outgoing token): fix not to discard remaining commma separated values

README.md
=> docs(readme): add an explanation for redis-cell

.circleci/config.yml
=> ci(config.yml): test markdowns only in the source mode

crates/interledger-btp/Cargo.toml, crates/interledger-ccp/Cargo.toml, crates/interledger-router/Cargo.toml
=> Add missing UUIDv4 feature imports

crates/interledger-stream/Cargo.toml, crates/interledger-stream/src/congestion.rs
Fixes https://github.com/interledger-rs/interledger-rs/issues/49
=> Decrease max_packet_amount by decrease_factor on F08 w/ no details

crates/ilp-node/src/main.rs, crates/ilp-node/src/node.rs, crates/ilp-node/tests/accounts_api.rs, crates/ilp-node/tests/btp.rs, crates/ilp-node/tests/exchange_rates.rs, crates/ilp-node/tests/node_settings_api.rs, crates/ilp-node/tests/three_nodes.rs, docker/run-testnet-bundle.js, docs/configuration.md
Closes https://github.com/interledger-rs/interledger-rs/issues/461
=> Group together node exchange rate configuration params

crates/interledger-packet/src/error.rs
Fixes https://github.com/interledger-rs/interledger-rs/issues/100
=> Include error name when debug printing ILP error codes

examples/eth-xrp-three-nodes/README.md
Closes https://github.com/interledger-rs/interledger-rs/issues/437.
I've also tested that manually adding `--ilp_address example.bob.charlie` when starting up the node does not affect the tests
=> Clarifications on ILP Address of Child nodes

.circleci/config.yml, crates/ilp-node/tests/btp.rs, crates/ilp-node/tests/test_helpers.rs, crates/ilp-node/tests/three_nodes.rs, crates/interledger-api/src/routes/accounts.rs, docs/api.md, examples/eth-settlement/README.md, examples/eth-xrp-three-nodes/README.md, examples/simple/README.md, examples/xrp-settlement/README.md, scripts/run-md-lib.sh, scripts/run-md-test.sh
Fixes https://github.com/interledger-rs/interledger-rs/issues/376
=> Show normalized amount and asset code when fetching an account's balance

crates/interledger-service-util/src/exchange_rates_service.rs
Fixes https://github.com/interledger-rs/interledger-rs/issues/499
=> Return proper error code in precision loss edge case in exchange rates service

README.md
fixes https://github.com/interledger-rs/interledger-rs/issues/423
=> chore: use --bin instead of -p to avoid recompiling in readme

crates/ilp-node/Cargo.toml, crates/interledger-api/Cargo.toml, crates/interledger-service-util/Cargo.toml, crates/interledger-store/Cargo.toml
This enables returning REDACTED for secrets instead of SECRET
Fixes https://github.com/interledger-rs/interledger-rs/issues/397
=> feat: update secrecy version

Cargo.lock, crates/interledger-api/Cargo.toml, crates/interledger-api/src/routes/accounts.rs, crates/interledger-api/src/routes/node_settings.rs, crates/interledger-http/Cargo.toml, crates/interledger-http/src/server.rs
Fixes https://github.com/interledger-rs/interledger-rs/issues/556
=> fix(api/http): Use SecretStrings for HTTP authorization secrets

Cargo.lock, crates/interledger-api/src/routes/accounts.rs, crates/interledger-errors/src/account_store_error.rs, crates/interledger-errors/src/btp_store_error.rs, crates/interledger-errors/src/create_account_error.rs, crates/interledger-errors/src/http_store_error.rs, crates/interledger-errors/src/node_store_error.rs, crates/interledger-service-util/Cargo.toml, crates/interledger-service-util/src/balance_service.rs, crates/interledger-service-util/src/max_packet_amount_service.rs, crates/interledger-service-util/src/rate_limit_service.rs, crates/interledger-service/src/lib.rs, crates/interledger-store/src/redis/mod.rs, crates/interledger-store/tests/redis/accounts_test.rs, crates/interledger-store/tests/redis/balances_test.rs, crates/interledger-store/tests/redis/btp_test.rs, crates/interledger-store/tests/redis/http_test.rs, crates/interledger-store/tests/redis/settlement_test.rs
=> Expand Tests and remove some redundant clone's

crates/ilp-node/src/instrumentation/trace.rs, crates/ilp-node/src/node.rs, docs/logging.md
Previously the responses of incoming requests were not traced. 
TODO: Figure out why logs are full of junk data from other packets
=> fix: trace incoming packet responses

Cargo.lock, crates/ilp-cli/Cargo.toml, crates/ilp-node/Cargo.toml, crates/interledger-api/Cargo.toml, crates/interledger-btp/Cargo.toml, crates/interledger-ccp/Cargo.toml, crates/interledger-errors/Cargo.toml, crates/interledger-http/Cargo.toml, crates/interledger-ildcp/Cargo.toml, crates/interledger-packet/Cargo.toml, crates/interledger-rates/Cargo.toml, crates/interledger-router/Cargo.toml, crates/interledger-service-util/Cargo.toml, crates/interledger-service/Cargo.toml, crates/interledger-settlement/Cargo.toml, crates/interledger-spsp/Cargo.toml, crates/interledger-store/Cargo.toml, crates/interledger-stream/Cargo.toml, crates/interledger/Cargo.toml
This commit also includes a git tag for `interledger-v1.0.0`.
=> feat: bump version of all crates to 1.0.0

crates/ilp-node/Cargo.toml
=> fix(node): enable logging by default

crates/interledger-settlement/src/core/engines_api.rs, crates/interledger-settlement/src/core/idempotency.rs
Some trait bounds could be loosened up
=> fix(settlement): remove static requirements on engine api

crates/ilp-cli/src/interpreter.rs, crates/ilp-cli/src/parser.rs, crates/ilp-node/Cargo.toml, crates/ilp-node/tests/redis/payments_incoming.rs, crates/ilp-node/tests/redis/redis_tests.rs, crates/interledger-api/src/routes/accounts.rs, crates/interledger-api/src/routes/test_helpers.rs, crates/interledger-store/src/redis/mod.rs, crates/interledger-stream/src/lib.rs, crates/interledger-stream/src/server.rs
Introduces a new ~~`/admin/incoming`~~ `/payments/incoming` WebSocket, allowing admins to monitor incoming payments in all accounts belonging to a node.
=> Introduce a websocket for all payment notifications

crates/ilp-node/src/instrumentation/google_pubsub.rs, crates/ilp-node/src/instrumentation/metrics.rs, crates/ilp-node/src/main.rs, crates/interledger-stream/src/packet.rs, crates/interledger-stream/src/server.rs
A few additional tweaks targeting unnecessary clones.
=> A few drive-bys more

crates/interledger-btp/src/lib.rs, crates/interledger-spsp/src/client.rs, crates/interledger-store/src/redis/mod.rs
This fixes new clippy lints with 1.48.
=> Clippy update for 1.48

.circleci/config.yml
=> Reduce instance size and disable clippy, audit to unblock pending PRs

.github/workflows/docker.yml
Remove todos, and fix a minor bug with the if statement field.
=> Ci housekepping, remove todos, etc..

Cargo.lock, crates/ilp-node/Cargo.toml, crates/ilp-node/build.rs, crates/ilp-node/src/instrumentation/google_pubsub.rs, crates/ilp-node/src/instrumentation/prometheus.rs, crates/ilp-node/src/main.rs, crates/ilp-node/src/node.rs, crates/interledger-rates/src/lib.rs
Fixes #680, adds tests for the existing behaviour, drops assumed defunct toml support.
=> Fix ilp-node --version

crates/interledger-service-util/src/exchange_rates_service.rs
Mitigates some floating-point errors in exchange_rates_service by changing order of operations. Did also some refactoring to enable better testing. Mitigates cases where exchange rate ratio and scale differences cancel each other out.
=> Change order of operations to reduce floating-point errors

crates/interledger-btp/src/lib.rs, crates/interledger-packet/src/packet.rs, crates/interledger-service-util/src/echo_service.rs, crates/interledger-service-util/src/max_packet_amount_service.rs, crates/interledger-store/src/account.rs, crates/interledger-store/src/redis/mod.rs, crates/interledger-stream/src/packet.rs
=> Clippy warnings in 1.52

.github/workflows/ci.yml, Cargo.lock, crates/ilp-cli/Cargo.toml, crates/ilp-node/Cargo.toml, crates/interledger-btp/Cargo.toml, crates/interledger-errors/Cargo.toml, crates/interledger-packet/Cargo.toml, crates/interledger-service-util/Cargo.toml, crates/interledger-service/Cargo.toml, crates/interledger-stream/Cargo.toml
This is a superset of dependabot PRs.
=> Bundled up dependency updates
